### ISSUE TITLE
showcase stuff in homepage for better visibility

### ISSUE THREAD

**Issue by eneajaho** [ngxtension/ngxtension-platform#125]
open to suggestions

**Comment by michael-small** [comment]
I have been directed to the project by various examples from utility authors, in blogs and videos. Perhaps a short video with a supercut of the videos showing the final implementation being used as-is by the library? I think a short video is always interesting to have on doc pages like this one, and it would add the actual voice of contributors the docs. If this is an avenue to pursue, I could try to make the cut (with respective author permissions).

Otherwise, I think three succinct examples would be a good amount. Useful utilities I have used that seem like they would be modest sized examples to embed: `injectQueryParams`, `filterNil`, and `computedFrom`. That is would be a primer from 3 major categories of the utils.
