### ISSUE TITLE
derivedAsync does not work with promises and requireSync combined

### ISSUE THREAD

**Issue by jan-23** [ngxtension/ngxtension-platform#510]
When using derivedAsync, the combination of Promises and requireSync: true does not work. With Observables it works fine.

```
  a = derivedAsync(() => Promise.resolve(1)); // OK
  b = derivedAsync(() => 2, { requireSync: true }); // OK
  c = derivedAsync(() => of(3), { requireSync: true }); // OK
  d = derivedAsync(() => Promise.resolve(4), { requireSync: true }); // Fails
``` 
d has the type `never`

https://stackblitz.com/edit/stackblitz-starters-alvmt2?file=src%2Fmain.ts

**Comment by jan-23** [comment]
I found the explanation in the code:
`Promises cannot be used with requireSync. Pass an initialValue or set requireSync to false.`

Are there any plans to support this configuration?

**Comment by eneajaho** [comment]
Hello @jan-23 
As you saw the comment, promises cannot be used with requireSync because of how they work. You cannot just call a service and gets it's current value, you either have to await it or call .then() on it. 

While with observables, they can be sync or async, that's why the option only works with observables. 

There is no plan to support that configuration. 

Closing this as not planned. 

Feel free to add any questions you may have here.
