### ISSUE TITLE
`linkedQueryParam` typing and null-value issues with object-values

### ISSUE THREAD

**Issue by sandrooco** [ngxtension/ngxtension-platform#530]
I just tried out the new `linkedQueryParam` helper. It's great - thanks a lot for adding this!

While trying to get it working with an object value, I stumbled onto two issues. First, let me show the code:

```
public readonly activePointer = linkedQueryParam<{
    layerid: string;
    objectid: number;
  }>('pointer', {
    parse: (value) => {
      const parsed: Record<string, string> = JSON.parse(value ?? '{}');

      return (
        parsed['layerid'] && parsed['objectid'] ? { ...parsed } : null
      ) as any;
    },
    stringify: (value) => JSON.stringify(value),
  });
```

### First problem - typing:
If I remove the `as any` assertion, it will throw a type error:
_Object literal may only specify known properties, and parse does not exist in type `LinkedQueryParamOptions`._ It seems like an overload has type conflicts, not sure what's the problem here.

### Second problem - null values:
There are cases in which I need to reset the value to `null`. As per the docs, the query param should be removed. This works with number and string values, but I couldn't get it working when using an object. The browser's url bar will look like this: `?pointer=null` which obviously is not what I expected.

### Repro
There's a stackblitz with repro: https://stackblitz.com/edit/stackblitz-starters-jeq1cdjq?file=src%2Fhome.component.ts
Note: Stackblitz doesn't populate query params to the browsers url bar, so you might need to copy the example to a local environment.

**Comment by eneajaho** [comment]
Hi @sandrooco 
I'll start with the second problem. 
When you set the value to `null`, on the `stringify` method, you're stringifying `null` too, so there you'll have to do a null check before stringifying, otherwise "null" as a string was being set as the value. 

```ts
  public readonly activePointer = linkedQueryParam<{ ... }>('pointer', {
    parse: (value) => { ... },
    stringify: (value) => (value ? JSON.stringify(value) : null), 
  });
```

Just tested this one, and it worked as expected.

**Comment by sandrooco** [comment]
@eneajaho You're absolutely right! Thanks for the example.
Do you have any inputs/best practice regarding the typing?

**Comment by eneajaho** [comment]
I was just testing the first problem, and the first thing I can see is that it's a little bit hard to get objects right. 

First thing: 

```ts
linkedQueryParam<{ layerid: string; objectid: number }>('pointer', {...})
```
You're telling TS that you will always have an object value, but in the parse fn you return null if those fields don't exist, so this breaks the type. 

Also, in the parsed, you have typed it as: `Record<string, string>`, but the value you have in your declaration is like: 
`{ layerid: string; objectid: number }`, so you have one string and one number, which also breaks the type. 

On these cases, personally I'd let the type to be inferred from the parse instead of manually putting the types in the declaration. So, removing the generic type should give you basically what the parse fn returns, and you don't have to fight it. 

```ts
  public readonly activePointer = linkedQueryParam('pointer', {
    parse: (value) => { ... }, // <- this should return the correct type instead of putting it directly in the generic
    stringify: (value) => (value ? JSON.stringify(value) : null), 
  });
```

--- 

On these cases when you have to have two fields only, I'd recommend to just have them inside two different signals. 

Before: 

```ts
public readonly activePointer = linkedQueryParam<{
    layerid: string;
    objectid: number;
  }>('pointer', {
    parse: (value) => {
      const parsed: Record<string, string> = JSON.parse(value ?? '{}');

      return (
        parsed['layerid'] && parsed['objectid'] ? { ...parsed } : null
      ) as any;
    },
    stringify: (value) => JSON.stringify(value),
  });
```

After: 

```ts
activePointer = {
  layerid: linkedQueryParam('activelayerid'), // this is string | null by default
  objectid: linkedQueryParam('activeobjectid', parse: paramToNumber()) // this is going to be number | null
}
```

When you want to update it: 

```ts
someMethod() {
  this.activePointer.layerid.set('some value here or just');
  this.activePointer.objectid.set('some value here or just')
}

resetPointer() {
  this.activePointer.layerid.set(null);
  this.activePointer.objectid.set(null);
}
```

And read the signals normally: 

```angular2html
<div>
  layerid : {{ activePointer.layerid() }}
  objectid : {{ activePointer.objectid() }}
</div>
```

**Comment by eneajaho** [comment]
Another example: 

https://github.com/ngxtension/ngxtension-platform/blob/main/apps/test-app/src/app/linked-query-param/linked-query-param-insideObject.component.ts

**Comment by sandrooco** [comment]
Thanks for your support including detailed explanations, @eneajaho! Closing this issue makes sense since the problem is rather in context of linting and poor typing of `JSON.parse`: the function itself is practically not typed at all which leads to unsafe access errors. Type inference works fine with this approach (though I needed to surpress linting for one line):
```
// eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
const parsed: Record<string, string> = JSON.parse(value ?? '{}');
return parsed['layerid'] && parsed['objectid']
        ? {
            // explicitely fill and type properties here to make type inference work for resulting signal
            layerid: parsed['layerid'],
            objectid: Number(parsed['objectid']),
          }
        : null;
```
